/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/mia-stream-deck/descriptor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plugin's descriptor */
        get: operations["getDescriptor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mia-stream-deck/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plugin's status */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mia-stream-deck/public/index.html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plugin's front */
        get: operations["getFrontIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mia-stream-deck/public/bundle.js": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plugin's front app */
        get: operations["getFrontApp"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mia-stream-deck/public/bundle.js.map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plugin's front app map */
        get: operations["getFrontAppMap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mia-stream-deck/api/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the tables' names */
        get: operations["getTables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mia-stream-deck/api/tables/{tablename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the command table */
        get: operations["getTableByName"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mia-stream-deck/api/execute-command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Execute the command */
        put: operations["executeCommand"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description JSON Error description */
        Error: {
            code: string;
            message: string;
        };
        TableName: string;
        /** @description Commands table description, contains an array for the lines which contains an array for the rows. Each row is a command. */
        Table: components["schemas"]["Command"][][];
        /** @description Differents command types descriptions */
        Command: {
            icon?: string;
            picture?: string;
            action: components["schemas"]["ActionEmpty"] | components["schemas"]["ActionInputString"] | components["schemas"]["ActionInputKey"] | components["schemas"]["ActionCommand"] | components["schemas"]["ActionPlugin"];
        };
        /** @description Empty command (an empty row in the table) */
        ActionEmpty: {
            /** @enum {string} */
            type: "EMPTY";
        };
        /** @description Input string (keyboard simulator) */
        ActionInputString: {
            /** @enum {string} */
            type: "INPUT-STRING";
            string: string;
            /** @description Add a 'enter' input at the end of the string (default : false) */
            enter?: boolean;
        };
        /** @description Input specific key (keyboard simulator) */
        ActionInputKey: {
            /** @enum {string} */
            type: "INPUT-KEY";
            key: string;
            /** @description Key + alt (default : false) */
            alt?: boolean;
            /** @description Key + ctrl (default : false) */
            ctrl?: boolean;
            /** @description Key + shift (default : false) */
            shift?: boolean;
        };
        /** @description Execute a command line (like in a terminal) (see https://nodejs.org/api/child_process.html) */
        ActionCommand: {
            /** @enum {string} */
            type: "COMMAND";
            command: string;
            /** @description Current working directory of the child process. Default: process.cwd(). */
            cwd?: string;
            /** @description Prepare child process to run independently of its parent process. Specific behavior depends on the platform (see options.detached). */
            detached?: boolean;
            /** @description Shell to execute the command with. See Shell requirements and Default Windows shell. Default: '/bin/sh' on Unix, process.env.ComSpec on Windows. */
            shell?: string;
            /** @description If true, runs command inside of a shell. */
            insideShell?: boolean;
        };
        /** @description Execute a plugin method */
        ActionPlugin: {
            /** @enum {string} */
            type: "PLUGIN";
            plugin: string;
            operationId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getDescriptor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plugin's descriptor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description An error occured */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plugin's status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": "ENABLED" | "INITIALIZED";
                };
            };
            /** @description An error occured */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getFrontIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plugin's front */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description An error occured */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getFrontApp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plugin's front app */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/javascript": string;
                };
            };
            /** @description An error occured */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getFrontAppMap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plugin's front app */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description An error occured */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getTables: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tables registered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableName"][];
                };
            };
            /** @description An error occured */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getTableByName: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tablename: components["schemas"]["TableName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Table registered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Table"];
                };
            };
            /** @description An error occured */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    executeCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Command"];
            };
        };
        responses: {
            /** @description Command running */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description An error occured */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
